import pytest
import pandas as pd
import numpy as np
import subprocess
import os
import glob

# Define paths and constants
BASE_DIR = os.path.dirname(__file__)
SCRIPT_PATH = os.path.join(BASE_DIR, "generate_geo_maps.py")
OUTPUT_DIR = os.path.join(BASE_DIR, "output")
# "Golden files" = a previously generated, manually-verified copy of the
# output CSVs, checked into `reference_output/`. They are the expected
# baseline that test_csv_outputs_against_reference (below, currently
# commented out) diffs newly generated output against, to catch
# unintended regressions in later runs.
REFERENCE_DIR = os.path.join(BASE_DIR, "reference_output")
YEAR = "2025"
END_USE_DIR = os.path.join(OUTPUT_DIR, f"{YEAR}_end_use")
# Current generate_geo_maps.py output is split per fuel (see remove_space())
# rather than into one combined file per sector/geography.
FUEL_SUFFIXES = ["electricity", "naturalgas", "distillate", "otherfuel"]
FILE_LIST = [
    f"{sector}_Cdiv_{geo}_amy2018_{fuel}.csv"
    for sector in ("Com", "Res")
    for geo in ("EMM", "State")
    for fuel in FUEL_SUFFIXES
]


@pytest.fixture(scope="module")
def run_generation_script():
    """Fixture to run the data generation script before tests."""
    # Ensure the output directory exists
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Run the script to generate all files
    # Using --force to ensure it runs even if files exist
    subprocess.run(
        ["python", SCRIPT_PATH, "--all", "--force"], check=True, capture_output=True, text=True
    )
    yield
    # Teardown: clean up generated files if necessary
    # for filename in os.listdir(OUTPUT_DIR):
    #     os.remove(os.path.join(OUTPUT_DIR, filename))


def test_file_generation(run_generation_script):
    """Test if all expected end-use energy/stock files are generated by
    the script, under output/{YEAR}_end_use/.
    """
    generated_files = os.listdir(END_USE_DIR)

    # Check for energy files
    for f in FILE_LIST:
        assert f in generated_files, f"{f} was not generated."

    # Check for stock files
    for f in FILE_LIST:
        stock_file = f.replace(".csv", "_Stock.csv")
        assert stock_file in generated_files, f"{stock_file} was not generated."


def compare_csv_files(file1_path, file2_path, tolerance=1e-6):
    """Compare two CSV files, checking for numeric differences."""
    df1 = pd.read_csv(file1_path)
    df2 = pd.read_csv(file2_path)

    # Basic checks
    assert df1.shape == df2.shape, (
        f"Shape mismatch between {os.path.basename(file1_path)} and {os.path.basename(file2_path)}"
    )
    assert df1.columns.equals(df2.columns), f"Column mismatch in {os.path.basename(file1_path)}"

    # Sort to ensure proper comparison
    sort_cols = ["End use", "CDIV"]
    df1 = df1.sort_values(by=sort_cols).reset_index(drop=True)
    df2 = df2.sort_values(by=sort_cols).reset_index(drop=True)

    # Compare non-numeric columns
    non_numeric_cols = df1.select_dtypes(exclude=np.number).columns
    pd.testing.assert_frame_equal(df1[non_numeric_cols], df2[non_numeric_cols])

    # Compare numeric columns with tolerance
    numeric_cols = df1.select_dtypes(include=np.number).columns
    pd.testing.assert_frame_equal(
        df1[numeric_cols], df2[numeric_cols], check_exact=False, atol=tolerance, rtol=tolerance
    )


# This is a regression/snapshot test: it doesn't check correctness from
# first principles, only that output hasn't drifted from a trusted
# baseline. To use it, populate `reference_output/` once with a golden
# copy of the output: run generate_geo_maps.py --all --force, manually
# verify that run's output/ is correct (e.g. via the test0x_*.ipynb
# notebooks in this dir, spot-checks against RECS/SEDS, and the
# sum-to-1 check in test_state_shares_sum_to_one), then copy that
# verified output/ tree into reference_output/ as the new baseline.
# Repeat the copy step deliberately whenever a change is expected to
# alter the numbers (e.g. an intentional mapping update).
# @pytest.mark.parametrize("filename", FILE_LIST)
# def test_csv_outputs_against_reference(run_generation_script, filename):
#     """Compares generated CSVs against a reference 'golden' version."""
#     # Compare energy file
#     generated_path = os.path.join(OUTPUT_DIR, filename)
#     reference_path = os.path.join(REFERENCE_DIR, filename)
#     assert os.path.exists(reference_path), \
#         f"Reference file not found: {reference_path}"
#     compare_csv_files(generated_path, reference_path)
#
#     # Compare stock file
#     stock_filename = filename.replace(".csv", "_Stock.csv")
#     generated_stock_path = os.path.join(OUTPUT_DIR, stock_filename)
#     reference_stock_path = os.path.join(REFERENCE_DIR, stock_filename)
#     assert os.path.exists(reference_stock_path), \
#         f"Reference file not found: {reference_stock_path}"
#     compare_csv_files(generated_stock_path, reference_stock_path)

# More tests can be added here to replicate the logic from the other notebooks,
# such as the JSON comparison and aggregation logic.


NON_STATE_COLS = {"Technology", "End use", "CDIV", "Total"}


def _state_geo_csv_paths():
    """Locate every Cdiv/State-geography output file (across fuels, the
    Stock variant, and the tech-level variant), skipping the Cdiv/EMM
    files -- those share the same CDIV row label but their columns are
    EMM regions, not states.
    """
    paths = []
    for subdir in ("end_use", "technology"):
        pattern = os.path.join(OUTPUT_DIR, f"*_{subdir}", "*_Cdiv_State_*.csv")
        paths.extend(glob.glob(pattern))
    return sorted(paths)


def test_state_shares_sum_to_one(run_generation_script):
    """Each row disaggregates a Census-division-level value out to its
    member states, so the state-column shares in a given row (one
    End use, or one Technology/End use, within one CDIV) must sum to 1.
    """
    csv_paths = _state_geo_csv_paths()
    assert csv_paths, f"No Cdiv/State output files found under {OUTPUT_DIR} to check."

    for csv_path in csv_paths:
        df = pd.read_csv(csv_path)
        state_cols = [c for c in df.columns if c not in NON_STATE_COLS]
        row_sums = df[state_cols].sum(axis=1)

        # A row with every state column at 0 means there was no data at
        # all for that End use/CDIV(/Technology) combination -- a real
        # degenerate case (e.g. a fuel with no consumption in that
        # division), not a disaggregation bug -- so it's excluded rather
        # than asserted to sum to 1.
        nonzero = row_sums[row_sums.abs() > 1e-9]
        bad = nonzero[(nonzero - 1).abs() > 1e-6]

        id_cols = [c for c in ("Technology", "End use", "CDIV") if c in df.columns]
        assert bad.empty, (
            f"{os.path.basename(csv_path)}: state shares do not sum to "
            f"1 for these rows:\n{df.loc[bad.index, id_cols].assign(sum=bad)}"
        )


def test_gap_row_present_and_sums_to_one(run_generation_script):
    """The ComStock "gap" row (see generate_geo_maps.process_gap_end_use)
    should be present in the commercial electricity outputs -- both
    end-use-level and technology-level, EMM and State, energy and stock --
    and sum to 1 across regions per CDIV, just like every other row. Real
    gap SDR data only covers electricity and has no per-technology
    breakdown, so the technology-level "gap" row is tagged Technology ==
    "all"; no other fuel's files should carry a "gap" row.
    """
    elec_paths = glob.glob(os.path.join(OUTPUT_DIR, "*_end_use", "Com_Cdiv_*_electricity*.csv"))
    elec_paths += glob.glob(os.path.join(OUTPUT_DIR, "*_technology", "Com_Cdiv_*_electricity*.csv"))
    assert elec_paths, "No commercial electricity output files found."

    for path in elec_paths:
        df = pd.read_csv(path)
        gap_rows = df[df["End use"] == "gap"]
        assert not gap_rows.empty, f"No 'gap' row found in {path}"
        if "Technology" in df.columns:
            assert (gap_rows["Technology"] == "all").all(), (
                f"'gap' row(s) in {path} should be tagged Technology == 'all'"
            )

        region_cols = [c for c in df.columns if c not in NON_STATE_COLS]
        row_sums = gap_rows[region_cols].sum(axis=1)
        nonzero = row_sums[row_sums.abs() > 1e-9]
        bad = nonzero[(nonzero - 1).abs() > 1e-6]
        assert bad.empty, f"'gap' row shares don't sum to 1 in {path}:\n{bad}"

    other_paths = [
        p
        for p in (
            glob.glob(os.path.join(OUTPUT_DIR, "*_end_use", "Com_Cdiv_*.csv"))
            + glob.glob(os.path.join(OUTPUT_DIR, "*_technology", "Com_Cdiv_*.csv"))
        )
        if "electricity" not in os.path.basename(p)
    ]
    for path in other_paths:
        df = pd.read_csv(path)
        assert (df["End use"] != "gap").all(), f"Unexpected 'gap' row found in {path}"


# This is a starting point. The complex comparisons from the notebooks,
# especially the plotting, are better suited for manual validation or a more
# sophisticated visual regression testing framework. However, the underlying
# data comparison logic can be implemented here as demonstrated.
